services:
  pgsql:
    image: 'pgvector/pgvector:0.8.0-pg17'
    container_name: '${COMPOSE_PROJECT_NAME}_pgsql'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: sport_booking,sport_booking_test
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-default}'
      POSTGRES_USER: '${DB_USER?:err}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
      - ./docker/pg/scripts:/docker-entrypoint-initdb.d
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-default}', '-U', '${DB_USER}']
      retries: 3
      timeout: 5s

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    # healthcheck:
    #   test: ['CMD', 'mc', 'ready', 'local']
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:latest
    container_name: '${COMPOSE_PROJECT_NAME}_redis'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
  
  grafana:
    image: grafana/grafana:latest
    # user: ${USER_ID}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - loki
    
  loki:
    image: grafana/loki:2.9.8
    volumes:
      - ./config/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
      
  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - ./logs:/var/log/app
      - ./config/promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9091:9090"
    restart: unless-stopped
    networks:
      - loki
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    network_mode: host # Not compatible with ports declaration. This service will expose port 9100.
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

networks:
  sail:
    driver: bridge
  loki:

volumes:
  sailpgsql:
  minio_data: {}
  grafana_data: {}
