// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/login.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['login'], true>
}
type MeGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['me'], false>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['logout'], false>
}
type AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/register.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/register_controller.ts').default['register'], true>
}
type UsersIdGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/user_controller.ts').default['show'], false>
}
export interface ApiDefinition {
  'login': {
    '$url': {
    };
    '$post': LoginPost;
  };
  'me': {
    '$url': {
    };
    '$get': MeGet;
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'auth': {
    'register': {
      '$url': {
      };
      '$post': AuthRegisterPost;
    };
  };
  'users': {
    ':userId': {
      '$url': {
      };
      '$get': UsersIdGet;
    };
  };
}
const routes = [
  {
    params: [],
    name: 'auth.login',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'auth.me',
    path: '/me',
    method: ["GET"],
    types: {} as MeGet,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
  {
    params: [],
    name: 'auth.register',
    path: '/auth/register',
    method: ["POST"],
    types: {} as AuthRegisterPost,
  },
  {
    params: ["userId"],
    name: 'users.show',
    path: '/users/:userId',
    method: ["GET"],
    types: {} as UsersIdGet,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
