// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/login.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['login'], true>
}
type AuthMeGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['me'], false>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/auth_controller.ts').default['logout'], false>
}
type AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/validators/register.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/register_controller.ts').default['register'], true>
}
type AuthSocialIdRedirectGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/social_controller.ts').default['redirect'], false>
}
type AuthSocialIdCallbackGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/social_controller.ts').default['callback'], false>
}
type AuthSocialIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/social_controller.ts').default['disconnect'], false>
}
type HealthGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/core/controllers/health_checks_controller.ts').default['handle'], false>
}
type ReservationsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/reservation/validators/reservation.ts')['createReservationValidator']>>
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['store'], true>
}
type ReservationsGet = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/reservation/validators/reservation.ts')['indexReservationsValidator']>>
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['index'], true>
}
type ReservationsIdGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['show'], false>
}
type ReservationsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['destroy'], false>
}
type ReservationsUpdatestatusIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/reservation/validators/reservation.ts')['updateReservationStatusValidator']>>
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['updateStatus'], true>
}
type ReservationsCleanupstartedPatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/reservation/controllers/reservations_controller.ts').default['cleanupStartedReservations'], false>
}
type SportequipmentsIdReservationsGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/reservation/controllers/sport_equipments_reservations_controller.ts').default['getByEquipment'], false>
}
type ReservationsIdInvitationPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/reservation/validators/reservation.ts')['updateInvitationStatusValidator']>>
  response: MakeTuyauResponse<import('../app/reservation/controllers/users_reservations_controller.ts').default['updateInvitationStatus'], true>
}
type UsersIdReservationsGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/reservation/controllers/users_reservations_controller.ts').default['getUserReservationsById'], false>
}
type SportEquipmentsGet = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/sport_equipments/validators/sport_equipment.ts')['indexSportEquipmentsValidator']>>
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['index'], true>
}
type SportequipmentsIdGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['show'], false>
}
type SportequipmentsIdOwnerGet = {
  request: unknown
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['showOwner'], false>
}
type SportequipmentsIdOwnerPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/sport_equipments/validators/owner.ts')['assignOwnerValidator']>>
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['assignOwner'], true>
}
type SportequipmentsIdOwnerDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['removeOwner'], false>
}
type SportequipmentsIdOwnerPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/sport_equipments/validators/owner.ts')['updateOwnerValidator']>>
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['updateOwner'], true>
}
type SportequipmentsOwnershipIdApprovePatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['approveOwnership'], false>
}
type SportequipmentsOwnershipIdRefusePatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/sport_equipments/controllers/sport_equipments_controller.ts').default['refuseOwnership'], false>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/user_controller.ts').default['show'], false>
}
type UsersIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/users/validators/user.ts')['updateUserValidator']>>
  response: MakeTuyauResponse<import('../app/users/controllers/user_controller.ts').default['update'], true>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/users/controllers/user_controller.ts').default['destroy'], false>
}
export interface ApiDefinition {
  'auth': {
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'me': {
      '$url': {
      };
      '$get': AuthMeGet;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
    'register': {
      '$url': {
      };
      '$post': AuthRegisterPost;
    };
    'social': {
      ':provider': {
        'redirect': {
          '$url': {
          };
          '$get': AuthSocialIdRedirectGet;
        };
        'callback': {
          '$url': {
          };
          '$get': AuthSocialIdCallbackGet;
        };
        '$url': {
        };
        '$delete': AuthSocialIdDelete;
      };
    };
  };
  'health': {
    '$url': {
    };
    '$get': HealthGet;
  };
  'reservations': {
    '$url': {
    };
    '$post': ReservationsPost;
    '$get': ReservationsGet;
    ':id': {
      '$url': {
      };
      '$get': ReservationsIdGet;
      '$delete': ReservationsIdDelete;
      'invitation': {
        '$url': {
        };
        '$patch': ReservationsIdInvitationPatch;
      };
    };
    'update-status': {
      ':id': {
        '$url': {
        };
        '$patch': ReservationsUpdatestatusIdPatch;
      };
    };
    'cleanup-started': {
      '$url': {
      };
      '$patch': ReservationsCleanupstartedPatch;
    };
  };
  'sport-equipments': {
    ':equip_numero': {
      'reservations': {
        '$url': {
        };
        '$get': SportequipmentsIdReservationsGet;
      };
    };
  };
  'users': {
    ':userId': {
      'reservations': {
        '$url': {
        };
        '$get': UsersIdReservationsGet;
      };
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      '$put': UsersIdPutPatch;
      '$patch': UsersIdPutPatch;
      '$delete': UsersIdDelete;
    };
  };
  'sport_equipments': {
    '$url': {
    };
    '$get': SportEquipmentsGet;
    ':equip_numero': {
      '$url': {
      };
      '$get': SportequipmentsIdGet;
      'owner': {
        '$url': {
        };
        '$get': SportequipmentsIdOwnerGet;
        '$post': SportequipmentsIdOwnerPost;
        '$delete': SportequipmentsIdOwnerDelete;
        '$patch': SportequipmentsIdOwnerPatch;
      };
    };
    'ownership': {
      ':ownershipId': {
        'approve': {
          '$url': {
          };
          '$patch': SportequipmentsOwnershipIdApprovePatch;
        };
        'refuse': {
          '$url': {
          };
          '$patch': SportequipmentsOwnershipIdRefusePatch;
        };
      };
    };
  };
}
const routes = [
  {
    params: [],
    name: 'auth.login',
    path: '/auth/login',
    method: ["POST"],
    types: {} as AuthLoginPost,
  },
  {
    params: [],
    name: 'auth.me',
    path: '/auth/me',
    method: ["GET"],
    types: {} as AuthMeGet,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/auth/logout',
    method: ["POST"],
    types: {} as AuthLogoutPost,
  },
  {
    params: [],
    name: 'auth.register',
    path: '/auth/register',
    method: ["POST"],
    types: {} as AuthRegisterPost,
  },
  {
    params: ["provider"],
    name: 'auth.social.create',
    path: '/auth/social/:provider/redirect',
    method: ["GET"],
    types: {} as AuthSocialIdRedirectGet,
  },
  {
    params: ["provider"],
    name: 'auth.social.callback',
    path: '/auth/social/:provider/callback',
    method: ["GET"],
    types: {} as AuthSocialIdCallbackGet,
  },
  {
    params: ["provider"],
    name: 'auth.social.disconnect',
    path: '/auth/social/:provider',
    method: ["DELETE"],
    types: {} as AuthSocialIdDelete,
  },
  {
    params: [],
    name: 'reservations.store',
    path: '/reservations',
    method: ["POST"],
    types: {} as ReservationsPost,
  },
  {
    params: [],
    name: 'reservations.index',
    path: '/reservations',
    method: ["GET"],
    types: {} as ReservationsGet,
  },
  {
    params: ["id"],
    name: 'reservations.show',
    path: '/reservations/:id',
    method: ["GET"],
    types: {} as ReservationsIdGet,
  },
  {
    params: ["id"],
    name: 'reservations.destroy',
    path: '/reservations/:id',
    method: ["DELETE"],
    types: {} as ReservationsIdDelete,
  },
  {
    params: ["id"],
    name: 'reservations.updateStatus',
    path: '/reservations/update-status/:id',
    method: ["PATCH"],
    types: {} as ReservationsUpdatestatusIdPatch,
  },
  {
    params: [],
    name: 'reservations.cleanupStartedReservations',
    path: '/reservations/cleanup-started',
    method: ["PATCH"],
    types: {} as ReservationsCleanupstartedPatch,
  },
  {
    params: ["equip_numero"],
    name: 'getByEquipment',
    path: '/sport-equipments/:equip_numero/reservations',
    method: ["GET"],
    types: {} as SportequipmentsIdReservationsGet,
  },
  {
    params: ["id"],
    name: 'invitation.update.status',
    path: '/reservations/:id/invitation',
    method: ["PATCH"],
    types: {} as ReservationsIdInvitationPatch,
  },
  {
    params: ["userId"],
    name: 'getUserReservationsById',
    path: '/users/:userId/reservations',
    method: ["GET"],
    types: {} as UsersIdReservationsGet,
  },
  {
    params: [],
    name: 'sport_equipments.index',
    path: '/sport_equipments',
    method: ["GET"],
    types: {} as SportEquipmentsGet,
  },
  {
    params: ["equip_numero"],
    name: 'sport_equipments.show',
    path: '/sport_equipments/:equip_numero',
    method: ["GET"],
    types: {} as SportequipmentsIdGet,
  },
  {
    params: ["equip_numero"],
    name: 'sport_equipments.owner.show',
    path: '/sport_equipments/:equip_numero/owner',
    method: ["GET"],
    types: {} as SportequipmentsIdOwnerGet,
  },
  {
    params: ["equip_numero"],
    name: 'sport_equipments.owner.store',
    path: '/sport_equipments/:equip_numero/owner',
    method: ["POST"],
    types: {} as SportequipmentsIdOwnerPost,
  },
  {
    params: ["equip_numero"],
    name: 'sport_equipments.owner.destroy',
    path: '/sport_equipments/:equip_numero/owner',
    method: ["DELETE"],
    types: {} as SportequipmentsIdOwnerDelete,
  },
  {
    params: ["equip_numero"],
    name: 'sport_equipments.owner.update',
    path: '/sport_equipments/:equip_numero/owner',
    method: ["PATCH"],
    types: {} as SportequipmentsIdOwnerPatch,
  },
  {
    params: ["ownershipId"],
    name: 'sport_equipments.owner.approve',
    path: '/sport_equipments/ownership/:ownershipId/approve',
    method: ["PATCH"],
    types: {} as SportequipmentsOwnershipIdApprovePatch,
  },
  {
    params: ["ownershipId"],
    name: 'sport_equipments.owner.refuse',
    path: '/sport_equipments/ownership/:ownershipId/refuse',
    method: ["PATCH"],
    types: {} as SportequipmentsOwnershipIdRefusePatch,
  },
  {
    params: ["userId"],
    name: 'users.show',
    path: '/users/:userId',
    method: ["GET","HEAD"],
    types: {} as UsersIdGetHead,
  },
  {
    params: ["userId"],
    name: 'users.update',
    path: '/users/:userId',
    method: ["PUT","PATCH"],
    types: {} as UsersIdPutPatch,
  },
  {
    params: ["userId"],
    name: 'users.destroy',
    path: '/users/:userId',
    method: ["DELETE"],
    types: {} as UsersIdDelete,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
