server:
  http_listen_port: 3100
  grpc_listen_port: 9096

positions:
  filename: /tmp/positions./tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

#local machine logs
scrape_configs:
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="logs"} |= "request completed"'
          stages:
            - json:
                expressions:
                  method: method
                  url: url
                  status: status
                  user_id: user_id
            - labels:
                method:
                status:
                user_id:
